#! / bin / bash

LOG_FILE=/var/log/update_script.log

apt-get update >> $LOG_FILE
apt-get upgrade >> $LOG_FILE


# need to use crontab:
#  $ crontab -e
#  add '0 4 * * 1 /path/to/file.sh' string to crontab file.
